# Generated by Django 4.2.6 on 2023-10-15 19:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("analysis_data", jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ImageAnalysis",
        ),
        migrations.DeleteModel(
            name="ZipUpload",
        ),
    ]
