# Generated by Django 4.2.6 on 2023-10-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0004_analysisresults_analyzed_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisresults",
            name="webp_images",
            field=models.JSONField(default=list),
        ),
    ]
