# Generated by Django 4.2.6 on 2023-10-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0005_analysisresults_webp_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_hash", models.CharField(max_length=32, unique=True)),
                ("analysis_data", models.JSONField(blank=True, null=True)),
                (
                    "webp_image_path",
                    models.FilePathField(
                        path="L:\\Repo\\FacialScape\\facialScape\\media"
                    ),
                ),
            ],
        ),
    ]
