# Generated by Django 4.2.6 on 2023-10-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0002_imageupload_delete_imageanalysis_delete_zipupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zip_file", models.FileField(upload_to="zips/")),
                ("analysis_data", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ImageUpload",
        ),
    ]
